export {default as HomePage } from "./HomePage"
export {default as RegistrationPage } from "./RegistrationPage"
export {default as LoginPage } from "./LoginPage"
export {default as DashboardPage } from "./DashboardPage"
export {default as StudentProfile } from "./StudentProfile"
export {default as ForgotPasswordPage } from "./ForgotPasswordPage"
export {default as Malaria } from "./Malaria"
export {default as ProfilePage } from "./ProfilePage"
export {default as Overview } from "./ModuleContent"
export {default as CertificatePage } from "./CertificatePage"
// export {default as NotificationPage } from "./NotificationPage"
